services:
  postgres-dev:
    image: postgres:16
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backups:/backups
      - ./restore_db.sh:/docker-entrypoint-initdb.d/restore_db.sh
    environment:
      POSTGRES_DB: ${DB_NAME_DEV}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      BACKUP_FILE: /backups/news-bot-database-10-10-2024.sql
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME_DEV}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network-dev
    command: >
      bash -c "
        chmod +x /docker-entrypoint-initdb.d/restore_db.sh &&
        docker-entrypoint.sh postgres
      "

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app-network-dev
    depends_on:
      - postgres-dev
  
  
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres-dev:
        condition: service_healthy
    environment:
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@postgres-dev:5432/${DB_NAME_DEV}
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: 
      - /bin/sh
      - -c
      - |
        chmod +x /app/script.sh
        ./script.sh
    networks:
      - app-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app-dev:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - .:/home/pwuser/app
    depends_on:
      - app-dev
    environment:
      - DISPLAY=:99
    cap_add:
      - SYS_ADMIN
    networks:
      - app-network-dev

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN_DEV}"
      - "app-dev:5000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN_DEV}
    ports:
      - "4040:4040"
    networks:
      - app-network-dev

volumes:
  postgres_data_dev:
  pgadmin_data:

networks:
  app-network-dev:
    name: app-network-dev