services:
  postgres-dev:
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME_DEV}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME_DEV}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network-dev

  redis-dev:
    image: redis:6
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD_DEV}
    networks:
      - app-network-dev

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_started
    environment:
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@postgres-dev:5432/${DB_NAME_DEV}
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD_DEV}
      - REDIS_DB=${REDIS_DB_DEV}
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: 
      - /bin/sh
      - -c
      - |
        chmod +x /app/script.sh
        ./script.sh
    networks:
      - app-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app-dev:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - .:/home/pwuser/app
    depends_on:
      - app-dev
    environment:
      - DISPLAY=:99
    cap_add:
      - SYS_ADMIN
    networks:
      - app-network-dev

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN_DEV}"
      - "app-dev:5000"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN_DEV}
    ports:
      - "4040:4040"
    depends_on:
      app-dev:
        condition: service_healthy
    networks:
      - app-network-dev

volumes:
  postgres_data_dev:

networks:
  app-network-dev:
    name: app-network-dev