version: '3.8'
services:
  production:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "38890773"
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - production
    environment:
      DB_PORT: "5432"
      DB_NAME: "news_bot"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "production"
    command: ["python", "app.py"]
