"""Bot table updated

Revision ID: 06907320e6f5
Revises: 0a6fddd12d0b
Create Date: 2024-09-10 10:49:53.264661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06907320e6f5'
down_revision = '0a6fddd12d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('background_color', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('dalle_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('run_frequency',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('last_run')
        batch_op.drop_column('url')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('alias',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('used_keywords', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('alias',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('run_frequency',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dalle_prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('background_color')
        batch_op.drop_column('icon')
        batch_op.drop_column('alias')

    # ### end Alembic commands ###

