"""erase test column

Revision ID: 0692c0dbb1bd
Revises: 8c438931e816
Create Date: 2024-07-18 11:54:07.597531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0692c0dbb1bd'
down_revision = '8c438931e816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
