"""Description of the migration

Revision ID: 0a6fddd12d0b
Revises: 82795e675cf1
Create Date: 2024-08-01 19:22:13.494068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '0a6fddd12d0b'
down_revision = '82795e675cf1'
branch_labels = None
depends_on = None

def column_exists(table, column):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    columns = inspector.get_columns(table)
    return any(c["name"] == column for c in columns)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        if column_exists('bot', 'grok_prompt'):
            batch_op.drop_column('grok_prompt')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        if not column_exists('bot', 'grok_prompt'):
            batch_op.add_column(sa.Column('grok_prompt', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###