"""Description Bot class updated v2

Revision ID: 25e42819be4a
Revises: e29732eca0db
Create Date: 2024-08-28 13:10:07.566238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e42819be4a'
down_revision = 'e29732eca0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Set default values for existing NULLs
    op.execute("UPDATE bot SET dalle_prompt = 'default_prompt' WHERE dalle_prompt IS NULL")
    op.execute("UPDATE bot SET url = 'https://default.url' WHERE url IS NULL")
    op.execute("UPDATE bot SET run_frequency = 1 WHERE run_frequency IS NULL")  # Add this line

    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('dalle_prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('run_frequency',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('run_frequency',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('dalle_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
