"""populate2

Revision ID: 3d0abfc75cac
Revises: 6a2fed17c6a5
Create Date: 2024-05-02 17:06:39.549314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0abfc75cac'
down_revision = '6a2fed17c6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_sites_id_fkey', 'bot', type_='foreignkey')
    op.drop_constraint('bot_articles_id_fkey', 'bot', type_='foreignkey')
    op.drop_constraint('bot_keywords_id_fkey', 'bot', type_='foreignkey')
    op.drop_constraint('bot_blacklist_id_fkey', 'bot', type_='foreignkey')
    op.drop_column('bot', 'articles_id')
    op.drop_column('bot', 'blacklist_id')
    op.drop_column('bot', 'keywords_id')
    op.drop_column('bot', 'sites_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('sites_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bot', sa.Column('keywords_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bot', sa.Column('blacklist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bot', sa.Column('articles_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bot_blacklist_id_fkey', 'bot', 'blacklist', ['blacklist_id'], ['id'])
    op.create_foreign_key('bot_keywords_id_fkey', 'bot', 'keyword', ['keywords_id'], ['id'])
    op.create_foreign_key('bot_articles_id_fkey', 'bot', 'article', ['articles_id'], ['id'])
    op.create_foreign_key('bot_sites_id_fkey', 'bot', 'site', ['sites_id'], ['id'])
    # ### end Alembic commands ###
