"""tables fix

Revision ID: 6a2fed17c6a5
Revises: f0de7d3fc565
Create Date: 2024-05-02 16:14:08.310426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2fed17c6a5'
down_revision = 'f0de7d3fc565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('sites_id', sa.Integer(), nullable=True))
    op.add_column('bot', sa.Column('keywords_id', sa.Integer(), nullable=True))
    op.add_column('bot', sa.Column('blacklist_id', sa.Integer(), nullable=True))
    op.add_column('bot', sa.Column('articles_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bot', 'article', ['articles_id'], ['id'])
    op.create_foreign_key(None, 'bot', 'site', ['sites_id'], ['id'])
    op.create_foreign_key(None, 'bot', 'keyword', ['keywords_id'], ['id'])
    op.create_foreign_key(None, 'bot', 'blacklist', ['blacklist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_column('bot', 'articles_id')
    op.drop_column('bot', 'blacklist_id')
    op.drop_column('bot', 'keywords_id')
    op.drop_column('bot', 'sites_id')
    # ### end Alembic commands ###
