"""category model add slack_channel column

Revision ID: a31e15301cb6
Revises: 3b35d19cdba7
Create Date: 2024-05-23 19:46:41.894488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31e15301cb6'
down_revision = '3b35d19cdba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_channel', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('slack_channel')

    # ### end Alembic commands ###
