"""update bot schema with insight columns

Revision ID: ac9ea16e4a5e
Revises: 07907320e6f5
Create Date: 2024-10-10 02:19:58.942594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9ea16e4a5e'
down_revision = '07907320e6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_run_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'ERROR', name='bot_status'), nullable=True))
        batch_op.add_column(sa.Column('last_run_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_run_status', sa.Enum('SUCCESS', 'FAILURE', name='run_status'), nullable=True))
        batch_op.add_column(sa.Column('run_count', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('run_count')
        batch_op.drop_column('last_run_status')
        batch_op.drop_column('last_run_time')
        batch_op.drop_column('status')
        batch_op.drop_column('next_run_time')

    # ### end Alembic commands ###

