"""update bot schema with insight columns

Revision ID: ac9ea16e4a5e
Revises: 07907320e6f5
Create Date: 2024-10-10 02:19:58.942594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = 'ac9ea16e4a5e'
down_revision = '07907320e6f5'
branch_labels = None
depends_on = None

def column_exists(table, column):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    columns = inspector.get_columns(table)
    return any(c["name"] == column for c in columns)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        if not column_exists('bot', 'next_run_time'):
            batch_op.add_column(sa.Column('next_run_time', sa.DateTime(), nullable=True))
        if not column_exists('bot', 'status'):
            batch_op.add_column(sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'ERROR', name='bot_status'), nullable=True))
        if not column_exists('bot', 'last_run_time'):
            batch_op.add_column(sa.Column('last_run_time', sa.DateTime(), nullable=True))
        if not column_exists('bot', 'last_run_status'):
            batch_op.add_column(sa.Column('last_run_status', sa.Enum('SUCCESS', 'FAILURE', name='run_status'), nullable=True))
        if not column_exists('bot', 'run_count'):
            batch_op.add_column(sa.Column('run_count', sa.Integer(), nullable=True))
        
        if column_exists('bot', 'name'):
            batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        if column_exists('bot', 'name'):
            batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        if column_exists('bot', 'run_count'):
            batch_op.drop_column('run_count')
        if column_exists('bot', 'last_run_status'):
            batch_op.drop_column('last_run_status')
        if column_exists('bot', 'last_run_time'):
            batch_op.drop_column('last_run_time')
        if column_exists('bot', 'status'):
            batch_op.drop_column('status')
        if column_exists('bot', 'next_run_time'):
            batch_op.drop_column('next_run_time')

    # ### end Alembic commands ###