"""Column upgrated add

Revision ID: cc42ebdd042f
Revises: cd7838bde5ef
Create Date: 2024-08-27 14:57:17.552387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc42ebdd042f'
down_revision = 'cd7838bde5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_keywords', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###

