"""Column time interval erased from category table

Revision ID: cd7838bde5ef
Revises: 0a6fddd12d0b
Create Date: 2024-08-27 14:50:34.388117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7838bde5ef'
down_revision = '0a6fddd12d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('time_interval')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_interval', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###

