"""Description Bot class updated

Revision ID: e29732eca0db
Revises: cc42ebdd042f
Create Date: 2024-08-28 13:06:30.073242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29732eca0db'
down_revision = 'cc42ebdd042f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_run', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('run_frequency', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.drop_column('run_frequency')
        batch_op.drop_column('url')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_run')

    # ### end Alembic commands ###

