name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Deploy to Development
      run: |
        echo "Starting deployment to Development environment..."
        # Ensure we're in the correct directory
        cd $GITHUB_WORKSPACE || exit 1
        
        # Fetch latest changes
        git fetch origin
        
        # Store current commit hash
        PREVIOUS_COMMIT=$(git rev-parse HEAD)
        
        # Pull latest changes from develop branch
        git pull origin develop
        
        # Function to start containers
        start_containers() {
          docker-compose -f docker-compose-dev.yml -p news-bot-dev up -d --build
          if [ $? -ne 0 ]; then
            echo "Failed to start containers"
            return 1
          fi
          return 0
        }
        
        # Function to stop containers
        stop_containers() {
          docker-compose -f docker-compose-dev.yml -p news-bot-dev down
        }
        
        # Function to perform health check
        health_check() {
          for i in {1..5}; do
            if curl -f http://localhost:5000/health; then
              return 0
            fi
            echo "Health check attempt $i failed. Retrying in 10 seconds..."
            sleep 10
          done
          return 1
        }
        
        # Function to rollback
        rollback() {
          echo "Rolling back to previous commit..."
          git reset --hard $PREVIOUS_COMMIT
          stop_containers
          start_containers
          if health_check; then
            echo "Rollback successful"
          else
            echo "Rollback failed. Manual intervention required."
            exit 1
          fi
        }
        
        # Main deployment logic
        stop_containers
        if start_containers; then
          echo "Waiting for services to start..."
          sleep 30
          if health_check; then
            echo "Deployment successful. Health check passed."
          else
            echo "Health check failed. Rolling back..."
            rollback
          fi
        else
          echo "Failed to start containers. Rolling back..."
          rollback
        fi

    - name: Deployment Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "Deployment to Development completed successfully!"
        else
          echo "Deployment to Development failed. Please check the logs for details."
        fi