name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Deploy to Development
      run: |
        echo "Starting deployment to Development environment..."
        # Ensure we're in the correct directory
        cd $GITHUB_WORKSPACE || exit 1
        
        # Fetch latest changes
        git fetch origin
        
        # Store current commit hash
        PREVIOUS_COMMIT=$(git rev-parse HEAD)
        
        # Pull latest changes from develop branch
        git pull origin develop
        
        # Start Docker services
        docker-compose -f docker-compose-dev.yml up -d --build
        
        echo "Waiting for services to start..."
        sleep 60
        
        # Perform health check
        if curl -f http://localhost:5000/health; then
          echo "Deployment successful. Health check passed."
        else
          echo "Health check failed. Rolling back..."
          git reset --hard $PREVIOUS_COMMIT
          docker-compose -f docker-compose-dev.yml up -d --build
          echo "Rollback complete."
          exit 1
        fi

    - name: Deployment Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "Deployment to Development completed successfully!"
        else
          echo "Deployment to Development failed. Please check the logs for details."
        fi
