name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Development
      run: |
        echo "Starting deployment to Development environment..."
        cd /Users/amananand/Desktop/AI Alpha/news-bots-v2.1/news-bots-v2
        git fetch origin
        PREVIOUS_COMMIT=$(git rev-parse HEAD)
        git pull origin develop
        docker-compose -f docker-compose-dev.yml up -d --build
        echo "Waiting for services to start..."
        sleep 60
        if curl -f http://localhost:5000/health; then
          echo "Deployment successful. Health check passed."
        else
          echo "Health check failed. Rolling back..."
          git reset --hard $PREVIOUS_COMMIT
          docker-compose -f docker-compose-dev.yml up -d --build
          echo "Rollback complete."
          exit 1
        fi
    - name: Deployment Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "Deployment to Development completed successfully!"
        else
          echo "Deployment to Development failed. Please check the logs for details."
        fi
