name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Deploy to Production
      run: |
        echo "Starting deployment to Production environment..."
        # Ensure we're in the correct directory
        cd $GITHUB_WORKSPACE || exit 1
        
        # Fetch latest changes
        git fetch origin
        
        # Store current commit hash
        PREVIOUS_COMMIT=$(git rev-parse HEAD)
        
        # Pull latest changes from main branch
        git pull origin main
        
        # Start Docker services
        docker-compose -f docker-compose.yml up -d --build
        
        echo "Waiting for services to start..."
        sleep 60
        
        # Perform health check
        if curl -f http://localhost:5001/health; then
          echo "Deployment successful. Health check passed."
        else
          echo "Health check failed. Rolling back..."
          git reset --hard $PREVIOUS_COMMIT
          docker-compose -f docker-compose.yml up -d --build
          echo "Rollback complete."
          exit 1
        fi

    - name: Deployment Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "Deployment to Production completed successfully!"
        else
          echo "Deployment to Production failed. Please check the logs for details."
        fi

    - name: Debug Information
      if: failure()
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of directory:"
        ls -la
        echo "Git status:"
        git status
        echo "Docker version:"
        docker --version
        echo "Docker Compose version:"
        docker-compose --version
